# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from echocue.auth.proto import auth_service_pb2 as echocue_dot_auth_dot_proto_dot_auth__service__pb2

GRPC_GENERATED_VERSION = "1.71.2"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in echocue/auth/proto/auth_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Authenticate = channel.unary_unary(
            "/echocue.auth.AuthService/Authenticate",
            request_serializer=echocue_dot_auth_dot_proto_dot_auth__service__pb2.AuthenticateRequest.SerializeToString,
            response_deserializer=echocue_dot_auth_dot_proto_dot_auth__service__pb2.AuthenticateResponse.FromString,
            _registered_method=True,
        )
        self.GetPermissionContext = channel.unary_unary(
            "/echocue.auth.AuthService/GetPermissionContext",
            request_serializer=echocue_dot_auth_dot_proto_dot_auth__service__pb2.PermissionContextRequest.SerializeToString,
            response_deserializer=echocue_dot_auth_dot_proto_dot_auth__service__pb2.PermissionContextResponse.FromString,
            _registered_method=True,
        )
        self.CheckPermission = channel.unary_unary(
            "/echocue.auth.AuthService/CheckPermission",
            request_serializer=echocue_dot_auth_dot_proto_dot_auth__service__pb2.PermissionCheckRequest.SerializeToString,
            response_deserializer=echocue_dot_auth_dot_proto_dot_auth__service__pb2.PermissionCheckResponse.FromString,
            _registered_method=True,
        )


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Authenticate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPermissionContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CheckPermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Authenticate": grpc.unary_unary_rpc_method_handler(
            servicer.Authenticate,
            request_deserializer=echocue_dot_auth_dot_proto_dot_auth__service__pb2.AuthenticateRequest.FromString,
            response_serializer=echocue_dot_auth_dot_proto_dot_auth__service__pb2.AuthenticateResponse.SerializeToString,
        ),
        "GetPermissionContext": grpc.unary_unary_rpc_method_handler(
            servicer.GetPermissionContext,
            request_deserializer=echocue_dot_auth_dot_proto_dot_auth__service__pb2.PermissionContextRequest.FromString,
            response_serializer=echocue_dot_auth_dot_proto_dot_auth__service__pb2.PermissionContextResponse.SerializeToString,
        ),
        "CheckPermission": grpc.unary_unary_rpc_method_handler(
            servicer.CheckPermission,
            request_deserializer=echocue_dot_auth_dot_proto_dot_auth__service__pb2.PermissionCheckRequest.FromString,
            response_serializer=echocue_dot_auth_dot_proto_dot_auth__service__pb2.PermissionCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("echocue.auth.AuthService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("echocue.auth.AuthService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Authenticate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/echocue.auth.AuthService/Authenticate",
            echocue_dot_auth_dot_proto_dot_auth__service__pb2.AuthenticateRequest.SerializeToString,
            echocue_dot_auth_dot_proto_dot_auth__service__pb2.AuthenticateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPermissionContext(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/echocue.auth.AuthService/GetPermissionContext",
            echocue_dot_auth_dot_proto_dot_auth__service__pb2.PermissionContextRequest.SerializeToString,
            echocue_dot_auth_dot_proto_dot_auth__service__pb2.PermissionContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CheckPermission(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/echocue.auth.AuthService/CheckPermission",
            echocue_dot_auth_dot_proto_dot_auth__service__pb2.PermissionCheckRequest.SerializeToString,
            echocue_dot_auth_dot_proto_dot_auth__service__pb2.PermissionCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
