# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from echocue.core.lexicon.proto import semantic_classification_pb2 as echocue_dot_core_dot_lexicon_dot_proto_dot_semantic__classification__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in echocue/core/lexicon/proto/semantic_classification_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SemanticClassificationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Classify = channel.unary_unary(
                '/echocue.lexicon.SemanticClassification/Classify',
                request_serializer=echocue_dot_core_dot_lexicon_dot_proto_dot_semantic__classification__pb2.SemanticClassificationRequest.SerializeToString,
                response_deserializer=echocue_dot_core_dot_lexicon_dot_proto_dot_semantic__classification__pb2.SemanticClassificationResult.FromString,
                _registered_method=True)


class SemanticClassificationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Classify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SemanticClassificationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Classify': grpc.unary_unary_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=echocue_dot_core_dot_lexicon_dot_proto_dot_semantic__classification__pb2.SemanticClassificationRequest.FromString,
                    response_serializer=echocue_dot_core_dot_lexicon_dot_proto_dot_semantic__classification__pb2.SemanticClassificationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'echocue.lexicon.SemanticClassification', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('echocue.lexicon.SemanticClassification', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SemanticClassification(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Classify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echocue.lexicon.SemanticClassification/Classify',
            echocue_dot_core_dot_lexicon_dot_proto_dot_semantic__classification__pb2.SemanticClassificationRequest.SerializeToString,
            echocue_dot_core_dot_lexicon_dot_proto_dot_semantic__classification__pb2.SemanticClassificationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
