"""comprehensive_init

Revision ID: 2edc56d9eef3
Revises:
Create Date: 2026-08-18 23:58:17.212842

"""

import warnings

import sqlalchemy as sa
from advanced_alchemy.types import (
    GUID,
    ORA_JSONB,
    Bool,
    DateTimeUTC,
    EncryptedString,
    EncryptedText,
    FernetBackend,
    JsonB,
    OneTimeCode,
    PasswordHash,
    StoredObject,
    TOTPSecret,
)
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from alembic import op
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

from echocue.auth.password import PBKDF2Hasher

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PBKDF2Hasher = PBKDF2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = "2edc56d9eef3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """Schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_model",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.PasswordHash(backend=sa.PBKDF2Hasher(), length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_model")),
    )
    with op.batch_alter_table("user_model", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_model_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_user_model_username"), ["username"], unique=True)

    op.create_table(
        "workflow_runs_model",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("tenant_id", sa.GUID(length=16), nullable=True),
        sa.Column("room_id", sa.String(length=64), nullable=False),
        sa.Column("persona_id", sa.GUID(length=16), nullable=True),
        sa.Column("persona_version", sa.Integer(), nullable=True),
        sa.Column("workflow_status", sa.String(length=16), nullable=False),
        sa.Column("trigger_type", sa.String(length=32), nullable=True),
        sa.Column("semantic_type", sa.String(length=32), nullable=False),
        sa.Column("push_action", sa.String(length=8), nullable=True),
        sa.Column("review_category", sa.String(length=64), nullable=True),
        sa.Column("review_note", sa.String(length=1024), nullable=True),
        sa.Column(
            "risk_categories",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("skip_reason", sa.String(length=256), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTimeUTC(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTimeUTC(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("pushed_to_client", sa.Boolean(), nullable=False),
        sa.Column("delivered_to_client", sa.Boolean(), nullable=False),
        sa.Column("global_rule_version", sa.Integer(), nullable=True),
        sa.Column("organization_rule_version", sa.Integer(), nullable=True),
        sa.Column("room_rule_version", sa.Integer(), nullable=True),
        sa.Column(
            "comment_window_stage",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "trigger_evaluation_stage",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "persona_context_stage",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "semantic_classification_stage",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "interest_stage",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "reply_stage",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "review_stage",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "client_delivery_stage",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_runs_model")),
    )
    with op.batch_alter_table("workflow_runs_model", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workflow_runs_model_persona_id"), ["persona_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_model_persona_version"), ["persona_version"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_model_push_action"), ["push_action"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_model_room_id"), ["room_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_model_semantic_type"), ["semantic_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_model_started_at"), ["started_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_model_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_model_trigger_type"), ["trigger_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_model_workflow_status"), ["workflow_status"], unique=False)

    op.create_table(
        "organization_model",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("owner_user_id", sa.GUID(length=16), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["user_model.id"],
            name=op.f("fk_organization_model_owner_user_id_user_model"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_model")),
    )
    with op.batch_alter_table("organization_model", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_organization_model_name"), ["name"], unique=True)
        batch_op.create_index(batch_op.f("ix_organization_model_owner_user_id"), ["owner_user_id"], unique=True)

    op.create_table(
        "account_certification_model",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("user_id", sa.GUID(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("organization_id", sa.GUID(length=16), nullable=True),
        sa.Column("certified_at", sa.DateTimeUTC(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTimeUTC(timezone=True), nullable=True),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization_model.id"],
            name=op.f("fk_account_certification_model_organization_id_organization_model"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_model.id"],
            name=op.f("fk_account_certification_model_user_id_user_model"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_certification_model")),
    )
    with op.batch_alter_table("account_certification_model", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_account_certification_model_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_account_certification_model_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_account_certification_model_user_id"), ["user_id"], unique=True)

    op.create_table(
        "organization_member_model",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("organization_id", sa.GUID(length=16), nullable=False),
        sa.Column("user_id", sa.GUID(length=16), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization_model.id"],
            name=op.f("fk_organization_member_model_organization_id_organization_model"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_model.id"],
            name=op.f("fk_organization_member_model_user_id_user_model"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_member_model")),
        sa.UniqueConstraint("organization_id", "user_id", name="uq_organization_member_user"),
    )
    with op.batch_alter_table("organization_member_model", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_organization_member_model_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_organization_member_model_role"), ["role"], unique=False)
        batch_op.create_index(batch_op.f("ix_organization_member_model_user_id"), ["user_id"], unique=False)

    op.create_table(
        "room_model",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("room_id", sa.String(length=64), nullable=False),
        sa.Column("room_kind", sa.String(length=32), nullable=False),
        sa.Column("owner_user_id", sa.GUID(length=16), nullable=True),
        sa.Column("organization_id", sa.GUID(length=16), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(room_kind = 'personal' AND owner_user_id IS NOT NULL AND organization_id IS NULL) OR (room_kind = 'organization' AND organization_id IS NOT NULL AND owner_user_id IS NULL)",
            name=op.f("ck_room_model_ck_room_owner_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization_model.id"],
            name=op.f("fk_room_model_organization_id_organization_model"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["user_model.id"],
            name=op.f("fk_room_model_owner_user_id_user_model"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room_model")),
    )
    with op.batch_alter_table("room_model", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_room_model_organization_id"), ["organization_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_room_model_owner_user_id"), ["owner_user_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_room_model_room_id"), ["room_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_room_model_room_kind"), ["room_kind"], unique=False)

    op.create_table(
        "room_authorization_model",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("room_id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.GUID(length=16), nullable=False),
        sa.Column("user_id", sa.GUID(length=16), nullable=False),
        sa.Column("access_scope", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("granted_by_user_id", sa.GUID(length=16), nullable=True),
        sa.Column("expires_at", sa.DateTimeUTC(timezone=True), nullable=True),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"],
            ["user_model.id"],
            name=op.f("fk_room_authorization_model_granted_by_user_id_user_model"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization_model.id"],
            name=op.f("fk_room_authorization_model_organization_id_organization_model"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["room_model.room_id"],
            name=op.f("fk_room_authorization_model_room_id_room_model"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_model.id"],
            name=op.f("fk_room_authorization_model_user_id_user_model"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room_authorization_model")),
        sa.UniqueConstraint(
            "room_id", "organization_id", "user_id", "access_scope", name="uq_room_authorization_grant"
        ),
    )
    with op.batch_alter_table("room_authorization_model", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_room_authorization_model_access_scope"), ["access_scope"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_room_authorization_model_granted_by_user_id"), ["granted_by_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_room_authorization_model_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_room_authorization_model_room_id"), ["room_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_room_authorization_model_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_room_authorization_model_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email"))
        batch_op.drop_index(batch_op.f("ix_user_username"))

    op.drop_table("user")
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_runs_persona_id"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_persona_version"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_push_action"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_room_id"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_semantic_type"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_started_at"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_trigger_type"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_workflow_status"))

    op.drop_table("workflow_runs")
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("room_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("persona_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("persona_version", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("workflow_status", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("trigger_type", sa.VARCHAR(length=32), autoincrement=False, nullable=True),
        sa.Column("semantic_type", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column("push_action", sa.VARCHAR(length=8), autoincrement=False, nullable=True),
        sa.Column("review_category", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column("review_note", sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
        sa.Column("risk_categories", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("skip_reason", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.Column("attempt_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("latency_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("pushed_to_client", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("delivered_to_client", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("global_rule_version", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("organization_rule_version", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("room_rule_version", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("comment_window_stage", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column(
            "trigger_evaluation_stage", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("persona_context_stage", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column(
            "semantic_classification_stage", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("interest_stage", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("reply_stage", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("review_stage", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("client_delivery_stage", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("sa_orm_sentinel", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_runs")),
    )
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workflow_runs_workflow_status"), ["workflow_status"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_trigger_type"), ["trigger_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_started_at"), ["started_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_semantic_type"), ["semantic_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_room_id"), ["room_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_push_action"), ["push_action"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_persona_version"), ["persona_version"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_persona_id"), ["persona_id"], unique=False)

    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("username", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("password_hash", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("sa_orm_sentinel", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)

    with op.batch_alter_table("room_authorization_model", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_room_authorization_model_user_id"))
        batch_op.drop_index(batch_op.f("ix_room_authorization_model_status"))
        batch_op.drop_index(batch_op.f("ix_room_authorization_model_room_id"))
        batch_op.drop_index(batch_op.f("ix_room_authorization_model_organization_id"))
        batch_op.drop_index(batch_op.f("ix_room_authorization_model_granted_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_room_authorization_model_access_scope"))

    op.drop_table("room_authorization_model")
    with op.batch_alter_table("room_model", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_room_model_room_kind"))
        batch_op.drop_index(batch_op.f("ix_room_model_room_id"))
        batch_op.drop_index(batch_op.f("ix_room_model_owner_user_id"))
        batch_op.drop_index(batch_op.f("ix_room_model_organization_id"))

    op.drop_table("room_model")
    with op.batch_alter_table("organization_member_model", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organization_member_model_user_id"))
        batch_op.drop_index(batch_op.f("ix_organization_member_model_role"))
        batch_op.drop_index(batch_op.f("ix_organization_member_model_organization_id"))

    op.drop_table("organization_member_model")
    with op.batch_alter_table("account_certification_model", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_certification_model_user_id"))
        batch_op.drop_index(batch_op.f("ix_account_certification_model_status"))
        batch_op.drop_index(batch_op.f("ix_account_certification_model_organization_id"))

    op.drop_table("account_certification_model")
    with op.batch_alter_table("organization_model", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organization_model_owner_user_id"))
        batch_op.drop_index(batch_op.f("ix_organization_model_name"))

    op.drop_table("organization_model")
    with op.batch_alter_table("workflow_runs_model", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_runs_model_workflow_status"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_model_trigger_type"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_model_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_model_started_at"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_model_semantic_type"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_model_room_id"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_model_push_action"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_model_persona_version"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_model_persona_id"))

    op.drop_table("workflow_runs_model")
    with op.batch_alter_table("user_model", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_model_username"))
        batch_op.drop_index(batch_op.f("ix_user_model_email"))

    op.drop_table("user_model")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
