"""workflow_runs_init

Revision ID: b1259bd538d1
Revises: 4b94ef12069d
Create Date: 2026-08-18 12:31:38.023688

"""

import warnings

import sqlalchemy as sa
from advanced_alchemy.types import GUID, ORA_JSONB, DateTimeUTC
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b1259bd538d1"
down_revision = "4b94ef12069d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """Schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_runs",
        sa.Column("id", GUID(length=16), nullable=False),
        sa.Column("tenant_id", GUID(length=16), nullable=True),
        sa.Column("room_id", sa.String(length=64), nullable=False),
        sa.Column("persona_id", GUID(length=16), nullable=True),
        sa.Column("persona_version", sa.Integer(), nullable=True),
        sa.Column("workflow_status", sa.String(length=16), nullable=False),
        sa.Column("trigger_type", sa.String(length=32), nullable=True),
        sa.Column("semantic_type", sa.String(length=32), nullable=False),
        sa.Column("push_action", sa.String(length=8), nullable=True),
        sa.Column("review_category", sa.String(length=64), nullable=True),
        sa.Column("review_note", sa.String(length=1024), nullable=True),
        sa.Column(
            "risk_categories",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("skip_reason", sa.String(length=256), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("started_at", DateTimeUTC(timezone=True), nullable=True),
        sa.Column("completed_at", DateTimeUTC(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("pushed_to_client", sa.Boolean(), nullable=False),
        sa.Column("delivered_to_client", sa.Boolean(), nullable=False),
        sa.Column("global_rule_version", sa.Integer(), nullable=True),
        sa.Column("organization_rule_version", sa.Integer(), nullable=True),
        sa.Column("room_rule_version", sa.Integer(), nullable=True),
        sa.Column(
            "comment_window_stage",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "trigger_evaluation_stage",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "persona_context_stage",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "semantic_classification_stage",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "interest_stage",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "reply_stage",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "review_stage",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "client_delivery_stage",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_runs")),
    )
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workflow_runs_persona_id"), ["persona_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_persona_version"), ["persona_version"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_push_action"), ["push_action"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_room_id"), ["room_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_semantic_type"), ["semantic_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_started_at"), ["started_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_trigger_type"), ["trigger_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_workflow_status"), ["workflow_status"], unique=False)

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_runs_workflow_status"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_trigger_type"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_started_at"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_semantic_type"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_room_id"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_push_action"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_persona_version"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_persona_id"))

    op.drop_table("workflow_runs")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
