# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aigc/core/lexicon/proto/semantic_classification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'aigc/core/lexicon/proto/semantic_classification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5aigc/core/lexicon/proto/semantic_classification.proto\x12\x0c\x61igc.lexicon\"A\n\x1dSemanticClassificationComment\x12\x12\n\ncomment_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x97\x01\n\x1dSemanticClassificationRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x12\n\ntext_batch\x18\x02 \x03(\t\x12\r\n\x05top_n\x18\x03 \x01(\x05\x12\x42\n\rcomment_batch\x18\x04 \x03(\x0b\x32+.aigc.lexicon.SemanticClassificationComment\"\x99\x01\n\x1fSemanticClassificationCandidate\x12\x31\n\rsemantic_type\x18\x01 \x01(\x0e\x32\x1a.aigc.lexicon.SemanticType\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x12\n\ncomment_id\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x01\"\xb7\x01\n\x1cSemanticClassificationResult\x12\x31\n\rsemantic_type\x18\x01 \x01(\x0e\x32\x1a.aigc.lexicon.SemanticType\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\r\n\x05top_n\x18\x03 \x01(\x05\x12\x41\n\ncandidates\x18\x04 \x03(\x0b\x32-.aigc.lexicon.SemanticClassificationCandidate*\xd2\x01\n\x0cSemanticType\x12\x1d\n\x19SEMANTIC_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n\x1aSEMANTIC_TYPE_PLAYFUL_JOKE\x10\x01\x12 \n\x1cSEMANTIC_TYPE_PERSONA_PRAISE\x10\x02\x12$\n SEMANTIC_TYPE_INTERACTIVE_PROMPT\x10\x03\x12\"\n\x1eSEMANTIC_TYPE_ATMOSPHERE_BOOST\x10\x04\x12\x17\n\x13SEMANTIC_TYPE_OTHER\x10\x05\x32}\n\x16SemanticClassification\x12\x63\n\x08\x43lassify\x12+.aigc.lexicon.SemanticClassificationRequest\x1a*.aigc.lexicon.SemanticClassificationResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aigc.core.lexicon.proto.semantic_classification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEMANTICTYPE']._serialized_start=635
  _globals['_SEMANTICTYPE']._serialized_end=845
  _globals['_SEMANTICCLASSIFICATIONCOMMENT']._serialized_start=71
  _globals['_SEMANTICCLASSIFICATIONCOMMENT']._serialized_end=136
  _globals['_SEMANTICCLASSIFICATIONREQUEST']._serialized_start=139
  _globals['_SEMANTICCLASSIFICATIONREQUEST']._serialized_end=290
  _globals['_SEMANTICCLASSIFICATIONCANDIDATE']._serialized_start=293
  _globals['_SEMANTICCLASSIFICATIONCANDIDATE']._serialized_end=446
  _globals['_SEMANTICCLASSIFICATIONRESULT']._serialized_start=449
  _globals['_SEMANTICCLASSIFICATIONRESULT']._serialized_end=632
  _globals['_SEMANTICCLASSIFICATION']._serialized_start=847
  _globals['_SEMANTICCLASSIFICATION']._serialized_end=972
# @@protoc_insertion_point(module_scope)
